FROM node:8


# setup workdir
WORKDIR /
WORKDIR /backend

# install dependencies
COPY / .
#COPY backend_start.sh .
#RUN chmod +x backend_start.sh
RUN git config --global url."https://".insteadOf git://
RUN npm install

# run the app when the container starts
CMD ["npm", "start"]
#CMD ["sh","-c","../blockchain truffle migrate --reset && npm start"]
